const figures = [
  {
    id: 1,
    name: "SEGA-Luminasta Frieren: Beyond Journey's End Frieren ~Maid Costume~ Figure",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "SEGA-Luminasta",
    character: "Frieren",
    image: "Images/0adf51d0-5ecd-474f-af26-0e695d93a160.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Frieren-Beyond-Journeys-Costume/dp/B0DY2MBX5Q",
    price: "37.49",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 2,
    name: "Taito Hatsune Miku Wonderland Figure ~Snow White~ Prize Figure",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Hatsune Miku",
    image: "Images/0dd80626-71c4-492a-8362-e177a34e0c69.jpg",
    link: "https://www.amazon.com/Hatsune-Wonderland-Figure-Snow-White/dp/B093XDT2VB",
    price: "32.09",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 3,
    name: "Taito-Hatsune Miku Figure - Fashion (Country Ver.)",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Hatsune Miku",
    image: "Images/1cdc5fba-3225-41ef-b6f7-a43f77a2ac64.jpg",
    link: "https://www.amazon.com/Taito-Hatsune-Miku-Figure-Fashion-Country/dp/B0DT267LN6",
    price: "38.938",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 4,
    name: "SEGA-Luminasta Frieren: Beyond Journey's End Fern ~Flower Garden~",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "SEGA-Luminasta",
    character: "Fern",
    image: "Images/2d7adefc-fae6-4f93-9220-4b56371c138f.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Frieren-Journeys-Flower-Garden/dp/B0DPY8NFSH",
    price: "29.88",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 5,
    name: "FuRyu Corporation-Hatsune Miku Noodle Stopper Figure -Rabbit Ear Hood Pajama Blue Color ver.-",
    series: "Vocaloid",
    manufacturer: "FuRyu",
    character: "Hatsune Miku",
    image: "Images/3f3e097b-f7e2-431e-89ce-07771b9b649f.jpg",
    link: "https://www.amazon.com/Corporation-Hatsune-Noodle-Stopper-Figure-Rabbit/dp/B0DXS9DSJ5",
    price: "39.99",
    salePrice: "34.99",
    type: "Figure",
  },
  {
    id: 6,
    name: "SEGA-Delicious in Dungeon PM Perching Figure Marcille",
    series: "Dungeon Meshi",
    manufacturer: "SEGA",
    character: "Marcille",
    image: "Images/3fc9ec8c-6135-4083-9635-04bbd13d8195.jpg",
    link: "https://www.amazon.com/SEGA-Delicious-Dungeon-Perching-Figure-Marcille/dp/B0DPY5J2Q7",
    price: "35.00",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 7,
    name: "FuRyu Corporation-Hatsune Miku Noodle Stopper Figure -Lollipop- Figure",
    series: "Vocaloid",
    manufacturer: "FuRyu",
    character: "Hatsune Miku",
    image: "Images/5b219d71-03c0-485f-8f7b-108860d803e7.jpg",
    link: "https://www.amazon.com/Corporation-Hatsune-Noodle-Stopper-Figure-Lollipop/dp/B0DQRBT1H5",
    price: "47.00",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 8,
    name: "Taito-Monogatari Series Desktop Cute Figure - Hitagi Senjougahara",
    series: "Monogatari",
    manufacturer: "Taito",
    character: "Hitagi Senjougahara",
    image: "Images/5cf46d79-c982-4a02-9520-6292a0e7b8d6.jpg",
    link: "https://www.amazon.com/Taito-Monogatari-Desktop-Cute-Figure-Senjougahara/dp/B0DZFWZXJX",
    price: "39.99",
    salePrice: "27.60",
    type: "Figure",
  },
  {
    id: 9,
    name: "Banpresto - Dragon Ball Z - Majin Buu (vs Super Saiyan 3 Son Goku) Match Makers Figure",
    series: "Dragon Ball Z",
    manufacturer: "Banpresto",
    character: "Majin Buu",
    image: "Images/5d4ee487-cde5-4df5-a2a4-59ef00483d42.jpg",
    link: "https://www.amazon.com/Banpresto-Dragon-Saiyan-Makers-Figure/dp/B0DQVD838T",
    price: "30.00",
    salePrice: "26.00",
    type: "Figure",
  },
  {
    id: 10,
    name: "Hatsune Miku Wonderland Figure ~ Cinderella~ Prize Figure",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Hatsune Miku",
    image: "Images/6ae737c2-d5d5-497a-a666-b02ec1575ece.jpg",
    link: "https://www.amazon.com/Taito-Hatsune-Wonderland-Cinderella-Multiple/dp/B09P73N4T7",
    price: "31.99",
    salePrice: "26.00",
    type: "Figure",
  },
  {
    id: 11,
    name: "FuRyu Corporation-Hatsune Miku Noodle Stopper Figure -Flower Fairy Anemone-",
    series: "Vocaloid",
    manufacturer: "FuRyu",
    character: "Hatsune Miku",
    image: "Images/6c056045-08aa-4659-9c1a-f810555d167f.jpg",
    link: "https://www.amazon.com/Corporation-Hatsune-Noodle-Stopper-Flower-Anemone/dp/B0DTJJBZCM",
    price: "42.33",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 12,
    name: "Ado Figure Winter Ver. 2025",
    series: "Ado",
    manufacturer: "Taito",
    character: "Ado",
    image: "Images/7df6bab3-4731-4fe7-8efb-790c5a102c9d.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 13,
    name: "SEGA-Luminasta Hatsune Miku Series Hatsune Miku Conceptual Series Vol.1 Figure",
    series: "Vocaloid",
    manufacturer: "SEGA-Luminasta",
    character: "Hatsune Miku",
    image: "Images/7e0d9429-bafa-4fa2-8a0e-24d0d6ee2b9c.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Hatsune-Conceptual-Vol-1-Figure/dp/B0DY2VNNJ5",
    price: "32.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 14,
    name: "Furyu - Demon Slayer - Rengoku Kyojuro Noodle Stopper Figure",
    series: "Demon Slayer",
    manufacturer: "Furyu",
    character: "Rengoku Kyojuro",
    image: "Images/8eb005f5-69ec-4d22-8968-f283af159ed4.jpg",
    link: "https://www.amazon.com/Furyu-Slayer-Rengoku-Kyojuro-Stopper/dp/B0BKQJD8LV",
    price: "39.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 15,
    name: "SEGA-Desktop×Decorate Collections Hatsune Miku x Love and Berry Dress Up and Dance! Hatsune Miku Berry Costume Ver.",
    series: "Vocaloid",
    manufacturer: "SEGA-Desktop×Decorate",
    character: "Hatsune Miku",
    image: "Images/11c4a1e6-b2fe-479e-b6ad-0f1f0066852d.jpg",
    link: "https://www.amazon.com/SEGA-Desktop%C3%97Decorate-Collections-Hatsune-Berry-Costume/dp/B0DTXJ1WQB",
    price: "29.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 16,
    name: "SEGA The Apothecary Diaries: Maomao PM Perching Figure Chocorose",
    series: "The Apothecary Diaries",
    manufacturer: "SEGA",
    character: "Maomao",
    image: "Images/42ed6c99-9f6a-4e99-87dd-fac9bf8d0300.jpg",
    link: "https://www.amazon.com/SEGA-Apothecary-Diaries-Perching-Chocorose/dp/B0D3YSDDST",
    price: "40.80",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 17,
    name: "Frieren: Beyond Journey's End - Desktop Cute - Frieren Trunk ver. Figure",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "Taito",
    character: "Frieren",
    image: "Images/52ef351b-68d6-47b3-9f07-4ff3d9ca2ff9.jpg",
    link: "https://www.amazon.com/Frieren-Beyond-Journeys-Desktop-Figure/dp/B0FTLZDYH9",
    price: "34.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 18,
    name: "FuRyu Corporation - Hatsune Miku Noodle Stopper Figure -Love Blazer Navy Color ver.-",
    series: "Vocaloid",
    manufacturer: "FuRyu",
    character: "Hatsune Miku",
    image: "Images/181c09a2-5e4a-4875-89d6-cf85d4f31da5.jpg",
    link: "https://www.amazon.com/FuRyu-Corporation-Hatsune-Noodle-Stopper/dp/B0DX2LXYQJ",
    price: "38.99",
    salePrice: "35.00",
    type: "Figure",
  },
  {
    id: 19,
    name: "Frieren: Beyond Journey's End Desktop Cute Figure - Fern",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "Taito",
    character: "Fern",
    image: "Images/281f909b-2492-45c1-aff0-ffb6636279c4.jpg",
    link: "https://www.amazon.com/Taito-Frieren-Beyond-Journeys-Desktop-Figure/dp/B0DTP8FM9N",
    price: "30.00",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 20,
    name: "FuRyu Corporation - Hatsune Miku Noodle Stopper Figure -Hatsune Miku Nardack ver.-",
    series: "Vocaloid",
    manufacturer: "FuRyu",
    character: "Hatsune Miku",
    image: "Images/0652c340-23ea-46a0-ae5a-24b74ec828a8.jpg",
    link: "https://www.amazon.com/FuRyu-Corporation-Hatsune-Stopper-Hatsune/dp/B0DMF7Q81P",
    price: "39.95",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 21,
    name: "SEGA-Street Fighter 6 PM Perching Figure Ryu",
    series: "Street Fighter",
    manufacturer: "SEGA",
    character: "Ryu",
    image: "Images/4526afad-8b84-4150-8e2f-c99a69bb7d26.jpg",
    link: "https://www.amazon.com/SEGA-Street-Fighter-Perching-Figure-Ryu/dp/B0DPY5SWJ9",
    price: "39.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 22,
    name: "Thunder Tech Hatsune Miku Birthday 2025 AMP+ Party Ver. Figure",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Hatsune Miku",
    image: "Images/032225e2-df4d-46c9-9203-e296035fb0c9.jpg",
    link: "https://www.amazon.com/Thunder-Tech-Hatsune-Birthday-Figure/dp/B0FV2SK47Y",
    price: "39.98",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 23,
    name: "Taito-Frieren: Beyond Journey's End Desktop Cute Figure - Frieren (Roomwear Ver.)",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "Taito",
    character: "Frieren",
    image: "Images/70962e38-edfb-4948-b690-cb4af346cb0c.jpg",
    link: "https://www.amazon.com/Taito-Frieren-Journeys-Desktop-Frieren-Roomwear/dp/B0DQQJX5LF",
    price: "37.00",
    salePrice: "33.00",
    type: "Figure",
  },
  {
    id: 24,
    name: "Taito-Hatsune Miku Figure - Fashion (Preppy Ver.)",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Hatsune Miku",
    image: "Images/74486cbd-0aea-4f1e-8b23-59a3493dfeed.jpg",
    link: "https://www.amazon.com/Thunder-Tech-Hatsune-Fashion-Figure/dp/B0FSQHLVBK",
    price: "45.00",
    salePrice: "29.99",
    type: "Figure",
  },
  {
    id: 25,
    name: "Sega-Luminasta Hatsune Miku Series Hatsune Miku Conceptual Series Vol.3 Figure",
    series: "Vocaloid",
    manufacturer: "Sega-Luminasta",
    character: "Hatsune Miku",
    image: "Images/2492854f-408e-4697-852b-15e87b1d8384.jpg",
    link: "https://www.amazon.com/Thunder-Tech-Luminasta-Hatsune-Conceptual/dp/B0FTRN917D",
    price: "34.99",
    salePrice: "32.50",
    type: "Figure",
  },
  {
    id: 26,
    name: "SEGA-Luminasta Hatsune Miku Series Hatsune Miku Conceptual Series Vol.2 Figure",
    series: "Vocaloid",
    manufacturer: "SEGA-Luminasta",
    character: "Hatsune Miku",
    image: "Images/98827620-66cc-43b4-873f-98e1b4565d48.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Hatsune-Conceptual-Vol-2-Figure/dp/B0F1PLV9K3",
    price: "34.99",
    salePrice: "29.99",
    type: "Figure",
  },
  {
    id: 27,
    name: "SEGA-Luminasta Mega Man Prize Figure",
    series: "Mega Man",
    manufacturer: "SEGA-Luminasta",
    character: "Rockman",
    image: "Images/a5bf3747-8c38-4b0e-9c1c-85d6735aad57.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Mega-Man-Prize-Figure/dp/B0DY2YT51P",
    price: "39.87",
    salePrice: "33.20",
    type: "Figure",
  },
  {
    id: 28,
    name: "SEGA-Luminasta TV Anime SPY x Family Yor Forger Thorn Princess ~Mission Extend~ Figure",
    series: "SPY x Family",
    manufacturer: "SEGA-Luminasta",
    character: "Yor Forger",
    image: "Images/a91bf6dd-454d-467f-b479-4f84548cc81e.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Family-Princess-Mission-Extend/dp/B0F1P9MB4L",
    price: "45.01",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 29,
    name: "Taito-Hatsune Miku Wonderland Figure ~Rapunzel~ Prize Figure",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Hatsune Miku",
    image: "Images/ac3c94d4-e1a4-4f26-af5c-899d898a0c2a.jpg",
    link: "https://www.amazon.com/Taito-Hatsune-Wonderland-Rapunzel-Multiple/dp/B09MB1BSXC",
    price: "38.95",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 30,
    name: "SEGA-Luminasta Jujutsu Kaisen Satoru Gojo Extermination Figure",
    series: "Jujutsu Kaisen",
    manufacturer: "SEGA-Luminasta",
    character: "Satoru Gojo",
    image: "Images/b6906212-7928-45fa-a0cc-b4d8463368f6.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Jujutsu-Kaisen-Satoru-Extermination/dp/B0F1P5BPGF",
    price: "36.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 31,
    name: "SEGA-Luminasta TV Anime DAN DA DAN Okarun(Transformed) Vol.2 Ver.1.5 Figure",
    series: "DAN DA DAN",
    manufacturer: "SEGA-Luminasta",
    character: "Okarun",
    image: "Images/bdce0467-2b78-4fdc-8ef2-08f2a1bb82fa.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Okarun-Transformed-Ver-1-5-Figure/dp/B0F1PP2ZXD",
    price: "37.90",
    salePrice: "29.90",
    type: "Figure",
  },
  {
    id: 32,
    name: "SEGA-Luminasta Jujutsu Kaisen Yuji Itadori Black Flash Figure",
    series: "Jujutsu Kaisen",
    manufacturer: "SEGA-Luminasta",
    character: "Yuji Itadori",
    image: "Images/c539bbaa-b69b-4e5b-a2d8-6f3e610bc8c4.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Jujutsu-Kaisen-Itadori-Figure/dp/B0DQQZQ19M",
    price: "36.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 33,
    name: "FuRyu - Oshi no Ko Noodle Stopper Figure - Akane Kurokawa: Have a Good Night",
    series: "Oshi no Ko",
    manufacturer: "FuRyu",
    character: "Akane Kurokawa",
    image: "Images/ccda6dc7-8058-4de1-af82-271a248fe126.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 34,
    name: "Banpresto - Frieren: Beyond Journey's End - Fern Bust Figure",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "Banpresto",
    character: "Fern",
    image: "Images/d118f947-fd16-4506-abb8-6b62259814f9.jpg",
    link: "https://www.amazon.com/Banpresto-Frieren-Beyond-Journeys-Figure/dp/B0DJTDSG7N",
    price: "23.00",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 35,
    name: "Taito-Sakura Miku Desktop Cute Figure (Cherry Cushion Ver.)",
    series: "Vocaloid",
    manufacturer: "Taito",
    character: "Sakura Miku",
    image: "Images/d8111d1e-db14-4926-8689-ee8b4b22c1f0.jpg",
    link: "https://www.amazon.com/Taito-Sakura-Desktop-Figure-Cherry-Cushion/dp/B0DT1ZZRCX",
    price: "42.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 36,
    name: "Banpresto - My Hero Academia - The Amazing Heroes - Vol.23: Hizashi Yamada (MHA)",
    series: "My Hero Academia",
    manufacturer: "Banpresto",
    character: "Hizashi Yamada",
    image: "Images/e1b63499-9ac1-4bbf-a0ce-528951eee475.jpg",
    link: "https://www.amazon.com/BanPresto-Academia-Amazing-Heroes-Hizashi/dp/B0B4VC3R33",
    price: "24.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 37,
    name: "Sega - Lycoris Recoil - Luminasta - Takina Inoue China Style Statue",
    series: "Lycoris Recoil",
    manufacturer: "Sega-Luminasta",
    character: "Takina Inoue",
    image: "Images/e8cfc109-cd87-45be-ab59-44137872108a.jpg",
    link: "https://www.amazon.com/Sega-Lycoris-Recoil-Luminasta-Takina/dp/B0DKXZFX8K",
    price: "28.79",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 38,
    name: "Hatsune Miku Noodle Stopper Figure -2025 Chinese New Year ver.-",
    series: "Vocaloid",
    manufacturer: "Furyu",
    character: "Hatsune Miku",
    image: "Images/f86af8da-05d9-4041-8e79-beca4cf5bc33.jpg",
    link: "https://www.goodsmileus.com/products/hatsune-miku-noodle-stopper-figure-2025-chinese-new-year-ver-14902",
    price: "33.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 39,
    name: "SEGA-Luminasta Frieren: Beyond Journey's End Frieren ~Flower Garden~",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "SEGA-Luminasta",
    character: "Frieren",
    image: "Images/fa69e125-cda7-4bee-a6bc-b9e1affbdad3.jpg",
    link: "https://www.amazon.com/SEGA-Luminasta-Frieren-Journeys-Flower-Garden/dp/B0DPY66VMV",
    price: "39.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 40,
    name: "SEGA - Frieren: Beyond Journey's End - Frieren PM Perching Prize Figure (I Have Ringlets Now Ver.)",
    series: "Frieren: Beyond Journey's End",
    manufacturer: "SEGA",
    character: "Frieren",
    image: "Images/fb447c69-5538-440f-a9d4-627e2e60c17d.jpg",
    link: "https://www.amazon.com/Sega-Frieren-Journeys-Perching-Ringlets/dp/B0DPZW6NJR",
    price: "35.99",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 41,
    name: "FuRyu Corporation-Hatsune Miku Noodle Stopper Figure -Flower Fairy Winter Cherry-",
    series: "Vocaloid",
    manufacturer: "FuRyu",
    character: "Hatsune Miku",
    image: "Images/fb657e5f-ae17-45e8-9747-47853b79104e.jpg",
    link: "https://www.amazon.com/FuRyu-Corporation-Hatsune-Stopper-Flower-Cherry/dp/B0F234DVX3",
    price: "48.80",
    salePrice: "43.99",
    type: "Figure",
  },
  {
    id: 42,
    name: "Demon Slayer: Kimetsu No Yaiba Noodle Stopper Statue -Hashibira Inosuke",
    series: "Demon Slayer",
    manufacturer: "Furyu",
    character: "Hashibira Inosuke",
    image: "Images/fc850554-94bf-469b-b2a2-5a8cf8cf0143.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 43,
    name: "Demon Slayer: Kimetsu no Yaiba Noodle Stopper Tomioka Giyu",
    series: "Demon Slayer",
    manufacturer: "Furyu",
    character: "Tomioka Giyu",
    image: "Images/ed98bfa3-8ae0-4670-ba4a-1715842b6bf8.jpg",
    link: "https://www.amazon.com/Furyu-Slayer-Kimetsu-Stopper-Tomioka/dp/B0G6M74SZH",
    price: "46.50",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 44,
    name: "Demon Slayer: Kimetsu no Yaiba Noodle Stopper Zenitsu Agatsuma",
    series: "Demon Slayer",
    manufacturer: "Furyu",
    character: "Zenitsu Agatsuma",
    image: "Images/979141f7-88d6-4be6-be77-46d262333352.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 45,
    name: "Demon Slayer: Kimetsu no Yaiba Noodle Stopper Tanjiro Kamado",
    series: "Demon Slayer",
    manufacturer: "Furyu",
    character: "Tanjiro Kamado",
    image: "Images/eb71a78b-5db3-4bc6-9e13-f80bff6d4fff.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 46,
    name: "Hunter X Hunter - Gon Noodle Stopper",
    series: "Hunter X Hunter",
    manufacturer: "Furyu",
    character: "Gon",
    image: "Images/6a82377a-056a-446c-beab-24f96a71756d.jpg",
    link: "https://www.amazon.com/Furyu-Figurine-Hunter-Stopper-4582655074514/dp/B0CSWW2K16",
    price: "34.93",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 47,
    name: "Mometaria JoJo's Bizarre Adventure Jonathan Joestar",
    series: "JoJo's Bizarre Adventure",
    manufacturer: "Banpresto",
    character: "Jonathan Joestar",
    image: "Images/bea238f7-c160-45a7-859d-42939e01ab6e.jpg",
    link: "https://www.amazon.com/YLQANONG-Jonathan-Adventure-Figurine-Ornaments/dp/B0FH6L1R82",
    price: "32.48",
    salePrice: "",
    type: "Figure",
  },
  {
    id: 48,
    name: "Banpresto - Gintama - Gintoki Sakata (20th Anniversary ver.), Vibration Stars Figure",
    series: "Gintama",
    manufacturer: "Banpresto",
    character: "Gintoki Sakata",
    image: "Images/a2b4dbb7-0f10-4901-a786-90a3e45e288e.jpg",
    link: "https://www.amazon.com/Banpresto-Gintama-Gintoki-Anniversary-Vibration/dp/B0DVM23NWJ",
    price: "30",
    salePrice: "23.35",
    type: "Figure",
  },
  {
    id: 49,
    name: "Banpresto - HOLOLIVE - #hololive IF - Amane Kanata, Relax Time Figure",
    series: "Hololive",
    manufacturer: "Banpresto",
    character: "Amane Kanata",
    image: "Images/2c204687-4f9c-4f8f-ad74-03459146b8f9.jpg",
    link: "https://www.amazon.com/Banpresto-HOLOLIVE-hololive-Kanata-Figure/dp/B0F35JXM7Q",
    price: "28.80",
    salePrice: "27.49",
    type: "Figure",
  },
  /*
  {
    id: ,
    name: "",
    series: "",
    manufacturer: "",
    character: "",
    image: "Images/",
    link: "",
    price: "",
    salePrice: "",
    type: "Figure",
  },
  */
];

const plushes = [
  {
    id: 1,
    name: "GS9841 Korilakkuma Holding Cherry Blossom",
    series: "Rilakkuma",
    manufacturer: "San-X Co.",
    character: "Korilakkuma",
    image: "Images/6c0c4136-14a9-4764-a194-3a93446cbb28.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 2,
    name: "Prize-Ducki-3WHT",
    series: "",
    manufacturer: "Bellzi",
    character: "Ducki",
    image: "Images/310995ab-d14b-47b6-926f-aaad06425541.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 3,
    name: "Puppet Plush Toy -Sakura Miko-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Sakura Miko",
    image: "Images/c6e08369-b06e-4269-bfcf-7667e02ba7c8.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 4,
    name: "Puppet Plush Toy -Houshou Marine-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Houshou Marine",
    image: "Images/8c06215e-486b-4e96-b4a8-39ba5f2f0e12.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 5,
    name: "Puppet Plush Toy -Tokino Sora-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Tokino Sora",
    image: "Images/57a2dc5c-692a-4a23-aa67-900e7f8f8904.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 6,
    name: "Puppet Plush Toy -Inugami Korone-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Inugami Korone",
    image: "Images/1027e1a3-d2e3-4cf2-85d5-dd9431b59172.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 20,
    name: "Puppet Plush Toy -Usada Pekora-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Usada Pekora",
    image: "Images/e6000976-e36b-482c-b2c1-eb24b9277607.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 21,
    name: "Puppet Plush Toy -Hoshimachi Suisei-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Hoshimachi Suisei",
    image: "Images/b74673fd-be85-4a09-9af8-a78a54770dc7.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 7,
    name: "Lying Down Big Plush Toy -Akai Haato-",
    series: "Hololive",
    manufacturer: "Furyu",
    character: "Akai Haato",
    image: "Images/dc51357e-2d31-4fca-bf58-ec3f93029d63.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 8,
    name: "Plush, Sonic the Hedgehog",
    series: "Sonic the Hedgehog",
    manufacturer: "Toy Factory",
    character: "Sonic",
    image: "Images/045eb3ff-e5dd-4df6-b8a1-8d2a03640108.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 9,
    name: "Mario",
    series: "Mario",
    manufacturer: "Toy Factory",
    character: "Mario",
    image: "Images/c80f775e-1b5b-455d-98b9-9c2ecdb17c68.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 10,
    name: "6\" Pikachu",
    series: "Pokémon",
    manufacturer: "Toy Factory",
    character: "Pikachu",
    image: "Images/be9a827a-1f3f-4a2a-80ce-b32ff420ecfa.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 11,
    name: "My Hero Academia Tomonui Plush Assort Seriese 2 -Shoto Todoroki-",
    series: "My Hero Academia",
    manufacturer: "Banpresto-Tomonui",
    character: "Shoto Todoroki",
    image: "Images/b0eee2d2-091f-4aa4-ad1d-8659fa34a237.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 12,
    name: "Pac-Man Ghost Asst.",
    series: "Pac-Man",
    manufacturer: "Toy Factory",
    character: "Triggered White Ghost",
    image: "Images/25c62933-4544-40fd-a0c1-fd7382244372.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 14,
    name: "14\" Charmander, Pokemon",
    series: "Pokémon",
    manufacturer: "Toy Factory",
    character: "Charmander",
    image: "Images/68937a60-4bba-45bb-9195-12c03d100fa2.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 15,
    name: "Snow Miku Potekoro Mascot M size 2011 ver.",
    series: "Vocaloid",
    manufacturer: "Piapro",
    character: "Snow Miku 2011 ver.",
    image: "Images/fa73ce48-c312-418e-bea1-648a66da0a5b.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 16,
    name: "Snow Miku Potekoro Mascot M size 2015 ver.",
    series: "Vocaloid",
    manufacturer: "Piapro",
    character: "Snow Miku 2015 ver.",
    image: "Images/9a8e49d1-20fe-4aaf-af77-0994ea592528.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 17,
    name: "13.7\" Onigiri Animals Backpack - Panda",
    series: "",
    manufacturer: "FUKUYA USA Inc.",
    character: "Panda",
    image: "Images/1e9bf119-b918-4d60-a081-d17fd7439153.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 18,
    name: "M Plush Hatsune Miku Conceptual Series Vol. 1",
    series: "Vocaloid",
    manufacturer: "Sega",
    character: "Hatsune Miku",
    image: "Images/a1d82eac-a3a7-440e-a0ab-6046a309a58a.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 19,
    name: "M Plush Hatsune Miku Conceptual Series Vol. 2",
    series: "Vocaloid",
    manufacturer: "Sega",
    character: "Hatsune Miku",
    image: "Images/cae568db-b275-462b-97e9-f139e784162b.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 22,
    name: "Large Yoshi Plush",
    series: "Super Mario Bros.",
    manufacturer: "Good Stuff",
    character: "Yoshi",
    image: "Images/30f202a3-029c-4a93-a2dd-968d5349bd41.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 23,
    name: "Mini Dino Triceratops Purple",
    series: "",
    manufacturer: "",
    character: "Triceratops",
    image: "Images/34331ba1-cdd7-47e9-9f78-63f8ffdc89cc.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 24,
    name: "5\" Mochi Kirby ASST. Series 3",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/47a550cc-f091-4471-b449-763f16c18019.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 25,
    name: "Sleeping Kirby",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/fcdd3711-0348-4c62-bafb-2381a7e3fc49.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 26,
    name: "Sweet Pink Ball",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/198167e1-61d9-41b1-b684-3532f81772ff.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 27,
    name: "Bedtime Kirby with Waddle Dee Plush",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/3cff5d76-ca2f-44c9-aa81-cc41e4a175be.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 28,
    name: "Plush Toy -Kirby with Marshmallow A-",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/02578857-4db8-4e1f-a6d1-efe80578c6d2.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 29,
    name: "Kirby with Star Mini Plush Toy",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/994110c3-bea0-4c0a-9f5e-ab5062a12de8.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 30,
    name: "Kirby with Big Invincible Candy Mini Plush Toy -Happy-",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/28235afc-0fc1-4709-936e-2ce5e9af8a24.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 31,
    name: "Plush Toy -Kirby Ice Cream Cup-",
    series: "Kirby",
    manufacturer: "",
    character: "Kirby",
    image: "Images/d8add110-a2f3-4b53-ab9a-aaf7ccaef860.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 32,
    name: "Takara Tomy Chainsaw Man Fuwakororin Big Size B 11\" Makima Plush Doll Devil Hunter",
    series: "Chainsaw Man",
    manufacturer: "Takara Tomy",
    character: "Makima",
    image: "Images/a4483334-1520-49cd-8cc5-bd7a6b720970.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  {
    id: 33,
    name: "Squishmallow Sega Sonic the Hedgehog SHADOW Holding GREEN CHAOS EMERALD GEM 8\"",
    series: "Sonic",
    manufacturer: "Squishmallow",
    character: "Shadow the Hedgehog",
    image: "Images/20bf6160-18dc-45f8-8e2b-001c4476ce69.jpg",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  /*
  {
    id: ,
    name: "",
    series: "",
    manufacturer: "",
    character: "",
    image: "Images/",
    link: "",
    price: "",
    salePrice: "",
    type: "Plush",
  },
  */
];